apiVersion: v1
kind: Service

metadata:
  name: api-gateway-service

spec:
  type: NodePort
  selector:
    app: api-gateway-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000