apiVersion: apps/v1
kind: Deployment

metadata:
  name: member-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-app
  template:
    metadata:
      labels:
        app: member-app
    spec:
      containers:
        - name: member-server
          image: wesawth3sun/member-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - configMapRef:
                name: member-config
            - secretRef:
                name: spring-secret
            - secretRef:
                name: member-secret

