apiVersion: v1
kind: Service

metadata:
  name: member-service

spec:
  type: NodePort
  selector:
    app: member-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # 외부에서 접속할 포트 번호