apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app

  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
        - name: ai-server
          image: wesawth3sun/ai-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
