apiVersion: v1
kind: Service

metadata:
  name: ai-service

spec:
  type: NodePort
  selector:
    app: ai-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
