apiVersion: v1
kind: Service

metadata:
  name: study-service

spec:
  type: NodePort
  selector:
    app: study-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003 # 외부에서 접속할 포트 번호