apiVersion: apps/v1
kind: Deployment

metadata:
  name: study-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-app
  template:
    metadata:
      labels:
        app: study-app
    spec:
      containers:
        - name: study-server
          image: wesawth3sun/study-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret

