apiVersion: v1
kind: Service

metadata:
  name: grow-study-service

spec:
  type: NodePort
  selector:
    app: grow-study-app
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
      nodePort: 30000