apiVersion: v1
kind: Service

metadata:
  name: grow-matching-service

spec:
  type: NodePort
  selector:
    app: grow-matching-app
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30000